### ISSUE TITLE
second test fails

### ISSUE THREAD

**Issue by tunnckoCore** [datetime/current-day-number#1]
Second test fails only on travis-ci machine with `node` version `v0.10.26`.
On my local machine with `v0.11.13` and `v0.10.29` passes.

**Comment by arthurvr** [comment]
@tunnckoCore Is this stil an issue? Currently all test are going fine, isn't it?

**Comment by tunnckoCore** [comment]
Hoho, maybe, I think I fixed it and forgot to close it.

Yep.
